@attendeeId = 62ae65022fa197321e588d44
@sessionId = 62ae65d92fa197321e588d4a
@jwt = eyJhbGciOiJFUzI1NiJ9.eyJkaXNwbGF5TmFtZSI6IkpvaG4gRG9lIDExIiwiZW1haWwiOiJzdXBlcmNvb2xAZ21haWwuY29tIiwiaWF0IjoxNjU2MzcwNjY1LCJpc3MiOiJhdHRlbmRvLWFwaSIsImF1ZCI6Imh0dHBzOi8vYXR0ZW5kby5jb20iLCJleHAiOjE2NTYzNzI0NjV9.93NCoO1ESLY9wqd7VLocY_kxkEM32IE98-7jgKM_YmER7m3Dje7iSBDoidYMi5pTf7y8HSK8f3Ue-SNqs7vSWg

GET http://localhost:6000/api/attendee/attendance/628c29af3d1f27ba7e44a070
Authorization: Bearer {{jwt}}
###

POST http://localhost:6000/api/attendee/attend/{{attendeeId}}
Content-Type: application/json

{
    "code": "C99",
    "session": "{{sessionId}}"
}

###

POST http://localhost:6000/api/attendee/attend-new
Content-Type: application/json

{
    "code": "zkmaf9",
    "session": "628c2a98752d6c1d904e32df",
    "name": "Jake 5"
}

###
POST http://localhost:6000/api/attendee/update-name/{{attendeeId}}
Content-Type: application/json
Authorization: Bearer {{jwt}}

{
    "name": "2st Sister"
}