@attendeeId = 62ae65022fa197321e588d44

GET http://localhost:6000/api/attendee/attendance/628c29af3d1f27ba7e44a070

###

POST http://localhost:6000/api/attendee/attend/{{attendeeId}}
Content-Type: application/json

{
    "code": "zkmaf9",
    "session": "62ae65d92fa197321e588d4a"
}

###

POST http://localhost:6000/api/attendee/attend-new
Content-Type: application/json

{
    "code": "zkmaf9",
    "session": "628c2a98752d6c1d904e32df",
    "name": "Jake 5"
}

###
POST http://localhost:6000/api/attendee/update-name/{{attendeeId}}
Content-Type: application/json

{
    "name": "1st Sister"
}