@jwt = eyJhbGciOiJFUzI1NiJ9.eyJkaXNwbGF5TmFtZSI6IkpvaG4gRG9lIDExIiwiZW1haWwiOiJzdXBlcmNvb2xAZ21haWwuY29tIiwiaWF0IjoxNjU5NjY4Mzg0LCJpc3MiOiJhdHRlbmRvLWFwaSIsImF1ZCI6Imh0dHBzOi8vYXR0ZW5kby5jb20iLCJleHAiOjE2NTk2NzAxODR9.U0QMWUg3lCirGqtfD-22UJNjxM23dR2I6Haw9-WzjG177MHZCoscXLwvh-J1WatHIr7lhRkSD8WqDPA2TRCE2A


### Register
POST http://localhost:6000/api/auth/register
Content-Type: application/json

{
    "displayName": "John Doe 11",
    "email": "supercool@gmail.com",
    "password": "12345678",
    "confirmPassword": "12345678"
}

### Login
POST http://localhost:6000/api/auth/login
Content-Type: application/json

{
  "email": "supercool@gmail.com",
  "password": "12345678"
}

### Logout
POST http://localhost:6000/api/auth/logout


### refresh jwt token
POST http://localhost:6000/api/auth/refresh
Authorization: Bearer {{jwt}}