@courseId = 123456789

### Get courses by id

GET http://localhost:6000/api/courses/attendance/{{courseId}}


### Create new course

POST http://localhost:6000/api/courses
Content-Type: application/json

{
    "name": "course1",
    "attendees": ["First Sister", "Second Sister", "Third Sister"],
    "admins": []
    
}

###

GET http://localhost:6000/api/courses/attendance/628c29af3d1f27ba7e44a06f

###