@courseId = 62ae65022fa197321e588d43
@jwt = eyJhbGciOiJFUzI1NiJ9.eyJkaXNwbGF5TmFtZSI6IkpvaG4gRG9lIDExIiwiZW1haWwiOiJzdXBlcmNvb2xAZ21haWwuY29tIiwiaWF0IjoxNjU5MTM0MTUyLCJpc3MiOiJhdHRlbmRvLWFwaSIsImF1ZCI6Imh0dHBzOi8vYXR0ZW5kby5jb20iLCJleHAiOjE2NTkxMzU5NTJ9.XHywtIk1jDL5e_CSHcya7QpPkZGe56Ye344X7JeNnkdHRxqtTf5s0YJpnORUDF2KIP7M4aCckUFQm_DYG9wIgw


### Get courses by id

GET http://localhost:6000/api/courses/attendance/{{courseId}}


### Create new course

POST http://localhost:6000/api/courses
Content-Type: application/json
Authorization: Bearer {{jwt}}

{
    "name": "course2",
    "attendees": ["First Sister", "Second Sister", "Third Sister"],
    "admins": ["6286cc528e5883ecc78861ac"]
    
}

###

GET http://localhost:6000/api/courses/attendance/628c29af3d1f27ba7e44a06f

###
# Get all courses by user
GET http://localhost:6000/api/courses
Authorization: Bearer {{jwt}}