### Create new participant

POST http://localhost:6000/api/participant
Content-Type: application/json

{
    "displayName": "John Doe 10",
    "email": "johndoe@google.com",
    "password": "12345678",
    "confirmPassword": "12345678"
}